const TARGET_TYPE = { MEMBER_ONLY: 'MEMBER_ONLY', GUEST_ONLY: 'GUEST_ONLY', COMMON: 'COMMON' };
const PARTICIPATION_TYPE = { SIMPLE: 'SIMPLE', FORM: 'FORM', ROULETTE: 'ROULETTE' };
const EVENT_STATUS = { SCHEDULED: 'SCHEDULED', ONGOING: 'ONGOING', CLOSED: 'CLOSED' };
const ENTRY_STATUS = { APPLIED: 'APPLIED', CANCELED: 'CANCELED', WON: 'WON', LOST: 'LOST' };
const USER_ROLE = { ADMIN: 'ADMIN', MEMBER: 'MEMBER' };

module.exports = { TARGET_TYPE, PARTICIPATION_TYPE, EVENT_STATUS, ENTRY_STATUS, USER_ROLE };
